// <auto-generated />
using BlazorApp.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211121205403_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorApp.Shared.Judge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Chair")
                        .HasColumnType("bit");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Headshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Judges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Zena is an accomplished executive across CPG and Technology marketing and general management. She recently joined Kimberly-Clark, leading the company’s global marketing teams and driving initiatives to accelerate digital transformation. She was previously at Google, where she was most recently in Business and Operations leadership roles running the US Chromebooks organization and subsequently starting a Global Growth team.",
                            Category = "Instant Impact",
                            Chair = true,
                            Company = "Kimberly-Clark",
                            FirstName = "Zena",
                            Headshot = "https://cdn.warc.com/Images/WARCSiteContent/landing-pages/awards/effectiveness/judges/zena-arnold.jpg",
                            LastName = "Srivatsa Arnold",
                            Role = "Chief Digital & Marketing Officer"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Suresh is also the Global Head of Marketing, HSBC Life. He has held various leadership roles in strategy, sales, products, media and advertising at HSBC, WPP and GSK. Suresh is the Co-chair for Male Allies Hong Kong, a BALANCE Ambassador, an Advisory Board Member of the CMO Council, and a Male Ally for UN Women.",
                            Category = "Sustained Growth",
                            Chair = true,
                            Company = "HSBC",
                            FirstName = "Suresh",
                            Headshot = "https://cdn.warc.com/Images/WARCSiteContent/landing-pages/awards/effectiveness/judges/suresh-balaji.jpg",
                            LastName = "Balaji",
                            Role = "Chief Marketing Officer, Asia Pacific"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Michael has worked on global brands since the beginning of his career. Starting at Ad Agencies DDB and Leo Burnett London, working on Volkswagen and McDonalds, he joined another global brand, Xbox, in 2008. Michael’s marketing campaigns aim to resonate through culture, while rethinking how Xbox can connect with completely new audiences.",
                            Category = "Collaboration & Culture",
                            Chair = true,
                            Company = "Xbox",
                            FirstName = "Michael",
                            Headshot = "https://cdn.warc.com/Images/WARCSiteContent/landing-pages/awards/effectiveness/judges/michael-flatt.jpg",
                            LastName = "Flatt",
                            Role = "Director, Global Integrated Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Akira brings over 30 years of aviation industry experience and has held multiple leadership roles within the company, including his previous role as VP of Products and Services. Akira has been named one of Asia’s Best Marketers and among the 50 Most Influential Global Marketing Leaders. He currently serves as an advisory member of several boards.",
                            Category = "Customer Experience",
                            Chair = true,
                            Company = "Japan Airlines",
                            FirstName = "Akira",
                            Headshot = "https://cdn.warc.com/Images/WARCSiteContent/landing-pages/awards/effectiveness/judges/akira-mitsumasu.jpg",
                            LastName = "Mitsumasu",
                            Role = "VP of CX, Data Analytics and Global Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "In December 2019, Ann Mukherjee joined Pernod Ricard North America as Chairman &amp; CEO. The first industry outsider and woman of colour to assume the position, she has demonstrated her ability to advance through ambiguity, while delivering both ROI and ROR (return on responsibility). Ann joined Pernod Ricard from S.C. Johnson and Company, as its first-ever Global Chief Marketing Officer.",
                            Category = "Brand Purpose",
                            Chair = true,
                            Company = "Pernod Ricard North America",
                            FirstName = "Ann",
                            Headshot = "https://cdn.warc.com/Images/WARCSiteContent/landing-pages/awards/effectiveness/judges/ann-mukherjee.jpg",
                            LastName = "Mukherjee",
                            Role = "Chairman & CEO"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Antonia leads PwC’s Global Marketing Organisation, which brings together all aspects of brand, digital, communications, thought leadership, marketing and business development. Previously, Antonia was the Chief Marketing Officer for Capita where she led a brand refresh and marketing transformation. Prior to that she ran global marketing for Thomson Reuters/ Refinitiv and spent ten years in marketing at Accenture.",
                            Category = "Business-to-Business",
                            Chair = true,
                            Company = "PwC Network",
                            FirstName = "Antonia",
                            Headshot = "https://cdn.warc.com/Images/WARCSiteContent/landing-pages/awards/effectiveness/judges/antonia-wade.jpg",
                            LastName = "Wade",
                            Role = "Global Chief Marketing Officer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
